delay: 600 # 每次检查的时间间隔，单位为秒(默认为600秒)(每次检测时间会在你设置的时延0.8-1.5倍之间随机波动)
headless: False # 设置为True时，程序会在后台运行，否则会打开浏览器窗口(默认为False)
username: "账号用户名" # 必填，账号
password: "密码" # 必填，密码
# 更多配置请参考readme中的配置说明
